i18n with single-quote exception Argument rangeInElement (9,25) endOffset must not exceed descriptor text range (38, 62) length (24)
jenkinsci/idea-stapler-plugin pull request #127
Opened 2022-11-25 07:02 UTC by jgreffe

Fixes #126 

- handle case of non-closed quotes
- unescape content before parsing

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2022-11-28 07:15 UTC, duemir requested changes
At first glance:

* It looks like there are unused imports:
* The logging should be done at `debug` level, not warning IMO (There is `Logger#debugValues(String, Collection)` which looks similar to what you are doing)

2022-11-28 10:27 UTC, jgreffe commented
> At first glance:
> 
> * It looks like there are unused imports:

Yes, I'll fix it.

> * The logging should be done at `debug` level, not warning IMO (There is `Logger#debugValues(String, Collection)` which looks similar to what you are doing)

Not sure here, this means when a user reports an issue, he has to change log level before sharing?

2022-12-13 03:24 UTC, duemir commented
> Not sure here, this means when a user reports an issue, he has to change log level before sharing?

And that is fine. Users are highly technical. 
The nature of logs is tracing method calls, not reporting a recoverable issue. 
Hence, debug level is more appropriate, in my opinion.

2023-02-13 00:15 UTC, duemir approved these changes

2023-02-13 00:16 UTC, merged